export const FETCH_LOGIN = {
  REQUEST: 'FETCH_LOGIN_REQUEST',
  SUCCEED: 'FETCH_LOGIN_SUCCEED',
  FAILED: 'FETCH_LOGIN_SUCCESS',
  RESET: 'FETCH_LOGIN_RESET',
}

export const FETCH_PROFILE = {
  REQUEST: 'FETCH_PROFILE_REQUEST',
  SUCCEED: 'FETCH_PROFILE_SUCCEED',
  FAILED: 'FETCH_PROFILE_SUCCESS',
  RESET: 'FETCH_PROFILE_RESET',
}

export const FETCH_REFRESH = {
  REQUEST: 'FETCH_REFRESH_REQUEST',
  SUCCEED: 'FETCH_REFRESH_SUCCEED',
  FAILED: 'FETCH_REFRESH_SUCCESS',
  RESET: 'FETCH_REFRESH_RESET',
}

export const FETCH_LOGOUT = {
  REQUEST: 'FETCH_LOGOUT_REQUEST',
  SUCCEED: 'FETCH_LOGOUT_SUCCEED',
  FAILED: 'FETCH_LOGOUT_SUCCESS',
  RESET: 'FETCH_LOGOUT_RESET',
}